### PR TITLE
[ui] edit-in-place for values of env vars [#8]

### PR DESCRIPTION
**Pull request by doublerebel**
Quick edit-in-place turns value span into input field.  Autosaves on blur.  Key is not editable.

### CODE REVIEW

**Comment by knownasilya** [comment]
@doublerebel can you rebase this over master, thanks!

**Comment by doublerebel** [comment]
@knownasilya no problem, rebased.

**Comment by knownasilya** [comment]
@doublerebel I've released a new version (0.5.0), update via the plugin manager in the latest strider version.

**Comment by doublerebel** [comment]
Thanks for the fast PR acceptance and version bump!  Glad I found Strider.

**Comment by knownasilya** [comment]
@doublerebel would love your help in making it better! If you are contributing often, we can add you to the repo as a contributor.

**Pull request merged**
